//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Data.Objects.DataClasses;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Data.Objects;
using System.Text;
using Celeriq.DataCore.EFDAL;
using nHydrate.EFCore.DataAccess;
using nHydrate.EFCore.EventArgs;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Data.Linq;

namespace Celeriq.DataCore.EFDAL.Entity
{
	/// <summary>
	/// The collection to hold 'DimensionStore' entities
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "5.2.0")]
	[EdmEntityTypeAttribute(NamespaceName = "Celeriq.DataCore.EFDAL.Entity", Name = "DimensionStore")]
	[Serializable]
	[DataContractAttribute(IsReference = true)]
	[nHydrate.EFCore.Attributes.FieldNameConstantsAttribute(typeof(Celeriq.DataCore.EFDAL.Entity.DimensionStore.FieldNameConstants))]
	[System.ComponentModel.DataAnnotations.MetadataType(typeof(Celeriq.DataCore.EFDAL.Interfaces.Entity.Metadata.DimensionStoreMetadata))]
	[nHydrate.EFCore.Attributes.EntityMetadata("DimensionStore", false, true, true, true, "", true, false, false, "dbo")]
	public partial class DimensionStore : nHydrate.EFCore.DataAccess.NHEntityObject, nHydrate.EFCore.DataAccess.IBusinessObject, Celeriq.DataCore.EFDAL.IEntityWithContext, System.ComponentModel.IDataErrorInfo, Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore, System.ICloneable, System.IEquatable<Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore>, nHydrate.EFCore.DataAccess.IAuditable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'DimensionStore' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'DIdx' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'DIdx' property")]
			DIdx,
			/// <summary>
			/// Field mapping for the 'DimensionStoreId' property
			/// </summary>
			[nHydrate.EFCore.Attributes.PrimaryKeyAttribute()]
			[System.ComponentModel.ReadOnlyAttribute(true)]
			[System.ComponentModel.Description("Field mapping for the 'DimensionStoreId' property")]
			DimensionStoreId,
			/// <summary>
			/// Field mapping for the 'Name' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Name' property")]
			Name,
			/// <summary>
			/// Field mapping for the 'RepositoryId' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'RepositoryId' property")]
			RepositoryId,
			/// <summary>
			/// Field mapping for the 'CreatedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedBy' property")]
			CreatedBy,
			/// <summary>
			/// Field mapping for the 'CreatedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedDate' property")]
			CreatedDate,
			/// <summary>
			/// Field mapping for the 'ModifiedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedBy' property")]
			ModifiedBy,
			/// <summary>
			/// Field mapping for the 'ModifiedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedDate' property")]
			ModifiedDate,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Method called when an instance of this class is created
		/// </summary>
		partial void OnCreated();

		/// <summary>
		/// Initializes a new instance of the Celeriq.DataCore.EFDAL.Entity.DimensionStore class
		/// </summary>
		public DimensionStore()
		{
			this.OnCreated();
		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'DimensionStore.DIdx' field.
		/// </summary>
		/// <remarks>Field: [DimensionStore].[DIdx], Not Nullable, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		[System.ComponentModel.DisplayName("DIdx")]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual long DIdx
		{
			get { return _dIdx; }
			set
			{
				if (value == _dIdx) return;
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<long>(value, "DIdx");
				//this.OnDIdxChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("DIdx");
				_dIdx = eventArg.Value;
				ReportPropertyChanged("DIdx");
				//this.OnDIdxChanged(eventArg);
			}
		}

		/// <summary>
		/// The property that maps back to the database 'DimensionStore.DimensionStoreId' field.
		/// </summary>
		/// <remarks>Field: [DimensionStore].[DimensionStoreId], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
		[DataMemberAttribute()]
		[System.ComponentModel.DisplayName("DimensionStoreId")]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.ReadOnly(true)]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual long DimensionStoreId
		{
			get { return _dimensionStoreId; }
			set
			{
				if (value == _dimensionStoreId) return;
				ReportPropertyChanging("DimensionStoreId");
				_dimensionStoreId = value;
				ReportPropertyChanged("DimensionStoreId");
			}
		}

		/// <summary>
		/// The property that maps back to the database 'DimensionStore.Name' field.
		/// </summary>
		/// <remarks>Field: [DimensionStore].[Name], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		[System.ComponentModel.DisplayName("Name")]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual string Name
		{
			get { return _name; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Name))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "DimensionStore.Name", GetMaxLength(FieldNameConstants.Name)));
				if (value == _name) return;
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<string>(value, "Name");
				//this.OnNameChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("Name");
				_name = eventArg.Value;
				ReportPropertyChanged("Name");
				//this.OnNameChanged(eventArg);
			}
		}

		/// <summary>
		/// The property that maps back to the database 'DimensionStore.RepositoryId' field.
		/// </summary>
		/// <remarks>Field: [DimensionStore].[RepositoryId], Not Nullable, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		[System.ComponentModel.DisplayName("RepositoryId")]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual int RepositoryId
		{
			get { return _repositoryId; }
			set
			{
				if (value == _repositoryId) return;
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<int>(value, "RepositoryId");
				//this.OnRepositoryIdChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("RepositoryId");
				_repositoryId = eventArg.Value;
				ReportPropertyChanged("RepositoryId");
				//this.OnRepositoryIdChanged(eventArg);
			}
		}

		/// <summary>
		/// The audit field for the 'Created By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual string CreatedBy
		{
			get { return _createdby; }
			protected internal set
			{
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<string>(value, "CreatedBy");
				//OnCreatedByChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("CreatedBy");
				_createdby = eventArg.Value;
				ReportPropertyChanged("CreatedBy");
				//OnCreatedByChanged(eventArg);
			}
		}

		/// <summary />
		protected string _createdby;

		/// <summary>
		/// The audit field for the 'Created Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual DateTime? CreatedDate
		{
			get { return _createddate; }
			protected internal set
			{
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<DateTime?>(value, "CreatedDate");
				//OnCreatedDateChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("CreatedDate");
				_createddate = eventArg.Value;
				ReportPropertyChanged("CreatedDate");
				//OnCreatedDateChanged(eventArg);
			}
		}

		/// <summary />
		protected DateTime? _createddate;

		/// <summary>
		/// The audit field for the 'Modified By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual string ModifiedBy
		{
			get { return _modifiedby; }
			protected internal set
			{
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<string>(value, "ModifiedBy");
				//OnModifiedByChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("ModifiedBy");
				_modifiedby = eventArg.Value;
				ReportPropertyChanged("ModifiedBy");
				//OnModifiedByChanged(eventArg);
			}
		}

		/// <summary />
		protected string _modifiedby;

		/// <summary>
		/// The audit field for the 'Modified Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual DateTime? ModifiedDate
		{
			get { return _modifieddate; }
			protected internal set
			{
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<DateTime?>(value, "ModifiedDate");
				//OnModifiedDateChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("ModifiedDate");
				_modifieddate = eventArg.Value;
				ReportPropertyChanged("ModifiedDate");
				//OnModifiedDateChanged(eventArg);
			}
		}

		/// <summary />
		protected DateTime? _modifieddate;

		/// <summary>
		/// The audit field for the 'Timestamp' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		[System.Diagnostics.DebuggerNonUserCode]
		public virtual byte[] Timestamp
		{
			get { return _timestamp; }
			protected internal set
			{
				var eventArg = new nHydrate.EFCore.EventArgs.ChangingEventArgs<byte[]>(value, "Timestamp");
				//OnTimestampChanging(eventArg);
				if (eventArg.Cancel) return;
				ReportPropertyChanging("Timestamp");
				_timestamp = eventArg.Value;
				ReportPropertyChanged("Timestamp");
				//OnTimestampChanged(eventArg);
			}
		}

		/// <summary />
		protected byte[] _timestamp;

		#endregion

		#region Property Holders

		/// <summary />
		protected long _dIdx;
		/// <summary />
		protected long _dimensionStoreId;
		/// <summary />
		protected string _name;
		/// <summary />
		protected int _repositoryId;

		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(FieldNameConstants field)
		{
			switch (field)
			{
				case FieldNameConstants.DIdx:
					return 0;
				case FieldNameConstants.DimensionStoreId:
					return 0;
				case FieldNameConstants.Name:
					return 50;
				case FieldNameConstants.RepositoryId:
					return 0;
			}
			return 0;
		}

		int nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(FieldNameConstants field)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type 'Celeriq.DataCore.EFDAL.Entity.DimensionStore.FieldNameConstants'.");

			switch ((FieldNameConstants)field)
			{
				case FieldNameConstants.DIdx: return typeof(long);
				case FieldNameConstants.DimensionStoreId: return typeof(long);
				case FieldNameConstants.Name: return typeof(string);
				case FieldNameConstants.RepositoryId: return typeof(int);
			}
			return null;
		}

		System.Type nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type 'Celeriq.DataCore.EFDAL.Entity.DimensionStore.FieldNameConstants'.");

			return GetFieldType((Celeriq.DataCore.EFDAL.Entity.DimensionStore.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type '" + this.GetType().ToString() + ".FieldNameConstants'.");
			return this.GetValue((FieldNameConstants)field, defaultValue);
		}

		void nHydrate.EFCore.DataAccess.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type '" + this.GetType().ToString() + ".FieldNameConstants'.");
			this.SetValue((FieldNameConstants)field, newValue);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Hold the primary key for this object
		/// </summary>
		protected nHydrate.EFCore.DataAccess.IPrimaryKey _primaryKey = null;
		nHydrate.EFCore.DataAccess.IPrimaryKey nHydrate.EFCore.DataAccess.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return null; }
		}

		#endregion

		#region IsParented

		/// <summary>
		/// Determines if this object is part of a collection or is detached
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		public virtual bool IsParented
		{
			get { return (this.EntityState != System.Data.EntityState.Detached); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Celeriq.DataCore.EFDAL.Entity.DimensionStore.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Celeriq.DataCore.EFDAL.Entity.DimensionStore.Clone(this);
			item._dimensionStoreId = 0;
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static DimensionStore Clone(Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore item)
		{
			var newItem = new DimensionStore();
			newItem.DIdx = item.DIdx;
			newItem.DimensionStoreId = item.DimensionStoreId;
			newItem.Name = item.Name;
			newItem.RepositoryId = item.RepositoryId;
			return newItem;
		}

		#endregion

		#region IsEquivalent

		/// <summary>
		/// Determines if all of the fields for the specified object exactly matches the current object.
		/// </summary>
		/// <param name="item">The object to compare</param>
		public override bool IsEquivalent(nHydrate.EFCore.DataAccess.INHEntityObject item)
		{
			return ((System.IEquatable<Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore>)this).Equals(item as Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore);
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public object GetValue(FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public object GetValue(FieldNameConstants field, object defaultValue)
		{
			if (field == FieldNameConstants.DIdx)
				return this.DIdx;
			if (field == FieldNameConstants.DimensionStoreId)
				return this.DimensionStoreId;
			if (field == FieldNameConstants.Name)
				return this.Name;
			if (field == FieldNameConstants.RepositoryId)
				return this.RepositoryId;
			if (field == FieldNameConstants.CreatedBy)
				return ((this.CreatedBy == null) ? defaultValue : this.CreatedBy);
			if (field == FieldNameConstants.CreatedDate)
				return ((this.CreatedDate == null) ? defaultValue : this.CreatedDate);
			if (field == FieldNameConstants.ModifiedBy)
				return ((this.ModifiedBy == null) ? defaultValue : this.ModifiedBy);
			if (field == FieldNameConstants.ModifiedDate)
				return ((this.ModifiedDate == null) ? defaultValue : this.ModifiedDate);
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == FieldNameConstants.DIdx)
			{
				this.DIdx = GlobalValues.SetValueHelperLongNotNullableInternal(newValue, "Field 'DIdx' does not allow null values!");
			}
			else if (field == FieldNameConstants.DimensionStoreId)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else if (field == FieldNameConstants.Name)
			{
				this.Name = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == FieldNameConstants.RepositoryId)
			{
				this.RepositoryId = GlobalValues.SetValueHelperIntNotNullableInternal(newValue, "Field 'RepositoryId' does not allow null values!");
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		/// <summary>
		/// The back navigation definition for walking [DimensionStore]->[DimensionData]
		/// Relationship Links: 
		/// [DimensionStore.DimensionStoreId = DimensionData.DimensionsionStoreId] (Required)
		/// </summary>
		[XmlIgnoreAttribute()]
		[SoapIgnoreAttribute()]
		[EdmRelationshipNavigationPropertyAttribute("Celeriq.DataCore.EFDAL.Entity", "FK__DimensionData_DimensionStore", "DimensionDataList")]
		public virtual EntityCollection<Celeriq.DataCore.EFDAL.Entity.DimensionData> DimensionDataList
		{
			get
			{
				//Eager load
				var retval = ((System.Data.Objects.DataClasses.IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Celeriq.DataCore.EFDAL.Entity.DimensionData>("Celeriq.DataCore.EFDAL.Entity.FK__DimensionData_DimensionStore", "DimensionDataList");
				if (!retval.IsLoaded  && this.EntityState != System.Data.EntityState.Added && this.EntityState != System.Data.EntityState.Detached)
				{
					retval.Load();
				}
				return retval;
			}
		}

		#region IDimensionStore Interface

		System.Collections.Generic.ICollection<Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionData> Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore.DimensionDataList
		{
			get { return (System.Collections.Generic.ICollection<Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionData>)(System.Collections.Generic.ICollection<DimensionData>)this.DimensionDataList; }
		}

		#endregion

		/// <summary>
		/// The navigation definition for walking [DimensionStore]->[RepositoryDefinition]
		/// Relationship Links: 
		/// [RepositoryDefinition.RepositoryId = DimensionStore.RepositoryId] (Required)
		/// </summary>
		[XmlIgnoreAttribute()]
		[SoapIgnoreAttribute()]
		[EdmRelationshipNavigationPropertyAttribute("Celeriq.DataCore.EFDAL.Entity", "FK__DimensionStore_RepositoryDefinition", "RepositoryDefinition")]
		public virtual RepositoryDefinition RepositoryDefinition
		{
			get
			{
				var retval = RepositoryDefinitionReference;
				if (!retval.IsLoaded && this.EntityState != System.Data.EntityState.Added && this.EntityState != System.Data.EntityState.Detached)
				{
					retval.Load();
				}
				return retval.Value;
			}
			set { ((System.Data.Objects.DataClasses.IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RepositoryDefinition>("Celeriq.DataCore.EFDAL.Entity.FK__DimensionStore_RepositoryDefinition", "RepositoryDefinition").Value = value; }
		}

		/// <summary>
		/// The navigation reference definition for walking RepositoryDefinition->DimensionStore
		/// </summary>
		[BrowsableAttribute(false)]
		protected virtual EntityReference<RepositoryDefinition> RepositoryDefinitionReference
		{
			get { return ((System.Data.Objects.DataClasses.IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RepositoryDefinition>("Celeriq.DataCore.EFDAL.Entity.FK__DimensionStore_RepositoryDefinition", "RepositoryDefinition"); }
			set
			{
				if ((value != null))
					((System.Data.Objects.DataClasses.IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RepositoryDefinition>("Celeriq.DataCore.EFDAL.Entity.FK__DimensionStore_RepositoryDefinition", "RepositoryDefinition", value);
			}
		}

		#region IDimensionStore Interface

		Celeriq.DataCore.EFDAL.Interfaces.Entity.IRepositoryDefinition Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore.RepositoryDefinition
		{
			get { return this.RepositoryDefinition; }
			set { this.RepositoryDefinition = (Celeriq.DataCore.EFDAL.Entity.RepositoryDefinition)value; }
		}

		#endregion

		#endregion

		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "didx": return "didx";
				case "dimensionstoreid": return "dimensionstoreid";
				case "name": return "name";
				case "repositoryid": return "repositoryid";
				case "createddate": return "createddate";
				case "createdby": return "createdby";
				case "modifieddate": return "modifieddate";
				case "modifiedby": return "modifiedby";
				case "timestamp": return "timestamp";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "didx": return "DimensionStore";
				case "dimensionstoreid": return "DimensionStore";
				case "name": return "DimensionStore";
				case "repositoryid": return "DimensionStore";
				case "createdby": return "DimensionStore";
				case "createddate": return "DimensionStore";
				case "modifiedby": return "DimensionStore";
				case "modifieddate": return "DimensionStore";
				case "timestamp": return "DimensionStore";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "didx": return "DimensionStore";
				case "dimensionstoreid": return "DimensionStore";
				case "name": return "DimensionStore";
				case "repositoryid": return "DimensionStore";
				case "createdby": return "DimensionStore";
				case "createddate": return "DimensionStore";
				case "modifiedby": return "DimensionStore";
				case "modifieddate": return "DimensionStore";
				case "timestamp": return "DimensionStore";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[didx\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[didx]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[dimensionstoreid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[dimensionstoreid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[name\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[name]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[repositoryid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[repositoryid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createdby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[createdby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[createddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifiedby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[modifiedby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifieddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[modifieddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[timestamp\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "DimensionStore") + "].[timestamp]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion

		#region DeleteData

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where)
		{
			return DeleteData(where, new nHydrate.EFCore.DataAccess.QueryOptimizer(), new ContextStartup(null), Celeriq.DataCore.EFDAL.DataCoreEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, nHydrate.EFCore.DataAccess.QueryOptimizer optimizer)
		{
			return DeleteData(where, optimizer, new ContextStartup(null), Celeriq.DataCore.EFDAL.DataCoreEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, string connectionString)
		{
			return DeleteData(where, new nHydrate.EFCore.DataAccess.QueryOptimizer(), new ContextStartup(null), connectionString);
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, nHydrate.EFCore.DataAccess.QueryOptimizer optimizer, ContextStartup startup, string connectionString)
		{
			if (optimizer == null)
				optimizer = new nHydrate.EFCore.DataAccess.QueryOptimizer();
				if (startup == null) startup = new ContextStartup(null);

			using (var connection = Celeriq.DataCore.EFDAL.DBHelper.GetConnection(Celeriq.DataCore.EFDAL.Util.StripEFCS2Normal(connectionString)))
			{
				using (var dc = new DataContext(connection))
				{
					var template = dc.GetTable<Celeriq.DataCore.EFDAL.DimensionStoreQuery>();
					using (var cmd = nHydrate.EFCore.DataAccess.BusinessEntityQuery.GetCommand<Celeriq.DataCore.EFDAL.DimensionStoreQuery>(dc, template, where))
					{
						if (startup.CommandTimeout != null && startup.CommandTimeout > 0) cmd.CommandTimeout = startup.CommandTimeout.Value;
						else cmd.CommandTimeout = 30;

						var parser = LinqSQLParser.Create(cmd.CommandText, LinqSQLParser.ObjectTypeConstants.Table);
						string sql = "SELECT [t0].[DimensionStoreId] INTO #t\r\n";
						sql += parser.GetFromClause(optimizer) + "\r\n";
						sql += parser.GetWhereClause();
						sql += "\r\n";

						var noLock = string.Empty;
						noLock = (optimizer.NoLocking ? "WITH (NOLOCK) " : string.Empty);
						sql += "DELETE [DimensionStore] FROM [dbo].[DimensionStore] " + noLock + "INNER JOIN #t ON [dbo].[DimensionStore].[DimensionStoreId] = #t.[DimensionStoreId]\r\n";
						sql += ";select @@rowcount";
						if (startup.IsAdmin) sql = LinqSQLParser.RemapTenantToAdminSql(sql);
						sql = "set ansi_nulls off;" + sql;
						cmd.CommandText = sql;
						dc.Connection.Open();
						var startTime = DateTime.Now;
						object p = cmd.ExecuteScalar();
						var endTime = DateTime.Now;
						optimizer.TotalMilliseconds = (long)endTime.Subtract(startTime).TotalMilliseconds;
						dc.Connection.Close();
						return (int)p;
					}
				}
			}
		}

		#endregion

		#region UpdateData

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, int? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, int?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Single? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Single?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, decimal? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, decimal?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, double? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, double?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, short? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, short?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, string newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, string newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, string newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, string>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, DateTime? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, DateTime?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, bool? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid? newValue)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid? newValue, string connectionString)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData(Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>> select, Expression<Func<Celeriq.DataCore.EFDAL.DimensionStoreQuery, bool>> where, Guid? newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Celeriq.DataCore.EFDAL.Entity.DimensionStore, Celeriq.DataCore.EFDAL.DimensionStoreQuery, Guid?>.UpdateData(select, where, newValue, "DimensionStore", GetDatabaseFieldName, true, null, connection, transaction);
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(DimensionStore.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "DIdx": return "DIdx";
				case "DimensionStoreId": return "DimensionStoreId";
				case "Name": return "Name";
				case "RepositoryId": return "RepositoryId";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

		#region Context

		DataCoreEntities IEntityWithContext.Context
		{
			get { return _internalContext; }
			set { _internalContext = value; }
		}
		private DataCoreEntities _internalContext = null;

		#endregion

		#region Auditing
		string nHydrate.EFCore.DataAccess.IAuditable.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		System.DateTime? nHydrate.EFCore.DataAccess.IAuditable.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		bool nHydrate.EFCore.DataAccess.IAuditable.IsCreateAuditImplemented
		{
			get { return true; }
		}

		bool nHydrate.EFCore.DataAccess.IAuditable.IsModifyAuditImplemented
		{
			get { return true; }
		}

		bool nHydrate.EFCore.DataAccess.IAuditable.IsTimestampAuditImplemented
		{
			get { return true; }
		}

		string nHydrate.EFCore.DataAccess.IAuditable.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		System.DateTime? nHydrate.EFCore.DataAccess.IAuditable.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		byte[] nHydrate.EFCore.DataAccess.IAuditable.TimeStamp
		{
			get { return this.Timestamp; }
		}

		internal virtual void ResetModifiedBy(string modifier)
		{
			if (this.ModifiedBy != modifier)
				this.ModifiedBy = modifier;
		}

		internal virtual void ResetCreatedBy(string modifier)
		{
			if (this.CreatedBy != modifier)
				this.CreatedBy = modifier;
			this.ResetModifiedBy(modifier);
		}
		#endregion

		#region Static Methods

		/// <summary>
		/// Creates and returns a metadata object for an entity type
		/// </summary>
		/// <returns>A metadata object for the entity types in this assembly</returns>
		public static Celeriq.DataCore.EFDAL.Interfaces.Entity.Metadata.DimensionStoreMetadata GetMetadata()
		{
			var a = typeof(DimensionStore).GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.MetadataTypeAttribute), true).FirstOrDefault();
			if (a == null) return null;
			var t = ((System.ComponentModel.DataAnnotations.MetadataTypeAttribute)a).MetadataClassType;
			if (t == null) return null;
			return Activator.CreateInstance(t) as Celeriq.DataCore.EFDAL.Interfaces.IMetadata as Celeriq.DataCore.EFDAL.Interfaces.Entity.Metadata.DimensionStoreMetadata;
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'DimensionStore' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		bool System.IEquatable<Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore>.Equals(Celeriq.DataCore.EFDAL.Interfaces.Entity.IDimensionStore other)
		{
			return this.Equals(other);
		}

		/// <summary>
		/// Compares two objects of 'DimensionStore' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Celeriq.DataCore.EFDAL.Entity.DimensionStore;
			if (other == null) return false;
			return (
				other.DIdx == this.DIdx &&
				other.DimensionStoreId == this.DimensionStoreId &&
				other.Name == this.Name &&
				other.RepositoryId == this.RepositoryId
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

		#region IDataErrorInfo
		/// <summary />
		string System.ComponentModel.IDataErrorInfo.Error
		{
			get { return this.GetObjectDataErrorInfo(); }
		}

		/// <summary />
		/// <param name="columnName"></param>
		/// <returns></returns>
		string System.ComponentModel.IDataErrorInfo.this[string columnName]
		{
			get
			{
				if (string.IsNullOrEmpty(columnName))
					return string.Empty;

				var retval = GetObjectPropertyDataErrorInfo(columnName);
				if (string.IsNullOrEmpty(retval))
				{
					switch (columnName.ToLower())
					{
						case "name":
							if (string.IsNullOrEmpty(this.Name) || string.IsNullOrEmpty(this.Name.Trim()))
								retval = "Name is required!";
							break;
						default:
							break;
					}

				}
				return retval;
			}
		}
		#endregion

	}

	partial class DimensionStore : nHydrate.EFCore.DataAccess.ICreatedAudit, nHydrate.EFCore.DataAccess.IModifiedAudit, nHydrate.EFCore.DataAccess.IConcurrencyAudit
	{
		#region ICreatedAudit Members

		string ICreatedAudit.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		DateTime? ICreatedAudit.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		#endregion

		#region IModifiedAudit Members

		string IModifiedAudit.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		DateTime? IModifiedAudit.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		#endregion

		#region IConcurrencyAudit Members

		byte[] IConcurrencyAudit.TimeStamp
		{
			get { return this.Timestamp; }
		}

		#endregion

	}

}

